services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - TZ=Europe/Belgrade
    networks:
      - coffee-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:8761/actuator/health | grep -q UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - D:/PMF/rzk/RZK/PROJEKAT/rzk/config-repo:/config-repo
    networks:
      - coffee-network
    restart: unless-stopped

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      eureka-server:
        condition: service_started
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - TZ=Europe/Belgrade
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - coffee-network
    restart: unless-stopped

  # -------------------------
  # DATABASES
  # -------------------------
  menu-db:
    image: mysql:8.4
    container_name: menu-db
    environment:
      - MYSQL_DATABASE=menu_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Belgrade
    ports:
      - "3307:3306"
    volumes:
      - menu_db_data:/var/lib/mysql
    networks:
      - coffee-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 20

  user-db:
    image: mysql:8.4
    container_name: user-db
    environment:
      - MYSQL_DATABASE=user_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Belgrade
    ports:
      - "3308:3306"
    volumes:
      - user_db_data:/var/lib/mysql
    networks:
      - coffee-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 20

  order-db:
    image: mysql:8.4
    container_name: order-db
    environment:
      - MYSQL_DATABASE=order_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Belgrade
    ports:
      - "3309:3306"
    volumes:
      - order_db_data:/var/lib/mysql
    networks:
      - coffee-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 20

  # -------------------------
  # SERVICES
  # -------------------------
  menu-service:
    build: ./menu-service
    container_name: menu-service
    depends_on:
      eureka-server:
        condition: service_started
      menu-db:
        condition: service_healthy
      config-server:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SERVER_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://menu-db:3306/menu_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Belgrade
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - coffee-network
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      eureka-server:
        condition: service_started
      user-db:
        condition: service_healthy
      config-server:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/user_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Belgrade
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - coffee-network
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      eureka-server:
        condition: service_started
      order-db:
        condition: service_healthy
      config-server:
        condition: service_started
      menu-service:
        condition: service_started
      user-service:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SERVER_PORT=8083
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://order-db:3306/order_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Belgrade
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - coffee-network
    restart: unless-stopped

networks:
  coffee-network:
    driver: bridge

volumes:
  menu_db_data:
  user_db_data:
  order_db_data: